### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/selection-api#111]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
@rniwa any chance of a quick update on the above before TPAC? We look forward  to seeing you there!

**Comment by rniwa** [comment]
Sorry for the delay. Hers's the reply:

* What progress has your spec made in the last 12 months?

Unfortunately, not much progress has been made other than some discussions in Github issues

* Is anything blocking your spec from moving to CR?

In my view, there are two aspects of the selection API: the parts of the API that's needed for interoperability and more of future looking API to be added. I think we should focus on spec'ing the former first and put it out as L1 CR. In general, we need to get more active discussion & spec editing to be done.

 * If yes, what is your plan to unblock it and do you need any help?

 * What do you want to achieve for your spec in the next two days (of breakout sessions)?

It's my fault that we haven't made much progress in this specification, and I'm hoping to allot a time to work on it more regularly to encourage more people to participate in the discussion & start editing more stuff in coming months.
