### ISSUE TITLE
Define getSelection on DocumentOrShadowRoot instead of Document

### ISSUE THREAD

**Issue by pmdartus** [w3c/selection-api#114]
Currently, the Selection API spec defines the `getSelection` via an extension to the [`Document` interface](https://w3c.github.io/selection-api/#extensions-to-document-interface). In the mean time, the Shadow DOM spec defines the `getSelection` via an exentsion to the [`DocumentOrShadowRoot` interface](https://w3c.github.io/webcomponents/spec/shadow/#extensions-to-the-documentorshadowroot-mixin). Does it makes more sense to define `getSelection` in the Selection API spec via a `DocumentOrShadowRoot` extension instead of a `Document` extension?

Note: There is already a WPT tests in place to test `getSelection` on `ShadowRoot`:
* https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/untriaged/elements-and-dom-objects/shadowroot-object/shadowroot-methods/test-004.html
* https://github.com/web-platform-tests/wpt/blob/master/shadow-dom/untriaged/user-interaction/ranges-and-selections/test-002.html

**Comment by rniwa** [comment]
See the current consensus at https://github.com/w3c/webcomponents/issues/79. The plan is not add getSelection but rather add getComposedRange to Selection interface.

**Comment by rniwa** [comment]
Closing in favor of the issue #98
