### ISSUE TITLE
containsNode could return true for a node that doesn't intersect the selection at all

### ISSUE THREAD

**Issue by pshaughn** [w3c/selection-api#116]
"If allowPartialContainment is true, the method must return true if and only if start of its range is before or visually equivalent to the first boundary point in the node or end of its range is after or visually equivalent to the last boundary point in the node. " is not what this should say.

Suppose I have nodes ABCD in that order, I've selected AB, and I'm asking containsNode("D",true). The start of its range is before D, so by this phrasing I should return true.

"If allowPartialContainment is true, the method must return true if and only if start of its range is before the _last_ boundary point in the node _and_ end of its range is after the _first_ boundary point in the node. " might be correct, but I haven't thought about it deeply enough to be sure.

**Comment by rniwa** [comment]
That looks right.
