### ISSUE TITLE
What task source do we queue events on?

### ISSUE THREAD

**Issue by pshaughn** [w3c/selection-api#117]
https://html.spec.whatwg.org/multipage/webappapis.html#queue-a-task wants the task source explicitly specified when queing tasks, but https://w3c.github.io/selection-api/#selectionchange-event isn't specifying.

**Comment by pshaughn** [comment]
(the answer is likely to be "the DOM manipulation task source" but that's not an automatic default)

**Comment by rniwa** [comment]
It's probably *user interaction task source* since the common case in which this event matters is in response to user modifying the selection via keyboard or pointing device.

**Comment by rniwa** [comment]
Fixed in https://github.com/w3c/selection-api/commit/5fea97d3b53e86d437ccff5a1476621556cf5fdb
