### ISSUE TITLE
What happens to direction when the range associated with the selection is modified?

### ISSUE THREAD

**Issue by darinadler** [w3c/selection-api#127]
The specification says that modifying the range associated with the selection modifies the selection. But I can’t find anything that specifies what happens to direction when that occurs. I’m assuming it should always be reset to _directionless_ if either endpoint of a range is modified, but I don’t see anything that defines that.

**Comment by rniwa** [comment]
Related to https://github.com/w3c/selection-api/issues/3

**Comment by annevk** [comment]
See also https://github.com/whatwg/dom/issues/772.

**Comment by rniwa** [comment]
Both Gecko & Blink maintains the original direction when using `selectNode`. https://jsfiddle.net/rdn30job/

**Comment by rniwa** [comment]
Added a clarification in https://github.com/w3c/selection-api/commit/fff9e059fcb5fa9f9c49bfa9c76219a21846068e

**Comment by darinadler** [comment]
I suggest we also get a test added to Web Platform Tests that covers this.
