### ISSUE TITLE
Add Selection.type to the spec

### ISSUE THREAD

**Issue by BenjamP** [w3c/selection-api#14]
Selection.type appears to be supported in Chrome and used on CKEditor. We should define it. It supports at least "None", "Caret", and "Range" as values.

**Comment by rniwa** [comment]
The comment in WebKit code indicates that IE returns "text" or "control".  Has that changed?

http://trac.webkit.org/browser/trunk/Source/WebCore/page/DOMSelection.idl

**Comment by BenjamP** [comment]
That was true for the legacy text selection object (document.selection), which is no longer supported in IE11. IE has never had this property on HTML5 selection (document.getSelection()

**Comment by Reinmar** [comment]
Hey. I'm not sure if this property really would make any difference. In fact, CKEditor has its own implementation of selection types which in our case are:
- "Text" is the default,
- "None" is set when there's no selection object or no ranges in the selection,
- "Element" is set when selection contains one "styleable" element (like img, table, td, etc.).

CKEditor uses the native type in some places, but most of that is for the old IEs' selection which @BenjamP mentioned and the rest is used in small portions of code (usually hacks for specific engines).

However, removing the type property from the engines will definitely break many editors. So, if not defining the type in the spec means that it may be gone soon, then I agree that it should be defined :).

**Comment by foolip** [comment]
Some use counter data from Chrome:
https://www.chromestatus.com/metrics/feature/timeline/popularity/404

**Comment by rniwa** [comment]
Added the attribute.  Please reopen the issue if the above commit is insufficient.

**Comment by foolip** [comment]
Thanks for this and the other fixes!
