### ISSUE TITLE
Should TreeWalker be expanded to support shadow roots in support of the selection API?

### ISSUE THREAD

**Issue by keithamus** [w3c/selection-api#164]
[WCCG had their spring F2F](https://github.com/WICG/webcomponents/issues/978#issuecomment-1516897276) in which this was discussed. Present members of WCCG identified an action item to raise this issue. You can read the full notes of the discussion ([WCCG had their spring F2F](https://github.com/WICG/webcomponents/issues/978#issuecomment-1516897276)) in which this was discussed, heading entitled "Selection API". I won't be quoting the notes for brevity.

TreeWalker was discussed as a mechanism to walk the DOM to gather textcontent of the currently selected nodes, but it was pointed out that TreeWalker does not iterate over shadow roots.

This issue is to discuss the expansion of TreeWalker to support shadow roots, perhaps using a `shadowroots:` option to provide contained shadow roots?

Refs #161

**Comment by rniwa** [comment]
TreeWalker is in a DOM specification so this issue should be tracked in https://github.com/whatwg/dom/ instead.
