### ISSUE TITLE
Change `getComposedRanges`'s `shadowRoots` parameter from rest parameter to a dictionary

### ISSUE THREAD

**Issue by siliu1** [w3c/selection-api#176]
Current [spec](https://w3c.github.io/selection-api/#ref-for-dom-selection-getcomposedranges-1) of `getComposedRanges` API has single `shadowRoots` parameter which is a rest parameter. We should change it to a dictionary that contains an array of shadow roots. Similar to https://html.spec.whatwg.org/#gethtmloptions. It'd be good to be consistent.

Proposed change:

```
sequence<StaticRange> getComposedRanges(optional GetComposedRangesOptions options = {});

dictionary GetComposedRangesOptions {
  sequence<ShadowRoot> shadowRoots = [];
};
```

**Comment by siliu1** [comment]
@mfreed7 FYI.

**Comment by mfreed7** [comment]
> @mfreed7 FYI.

LGTM! Thanks.

**Comment by smaug----** [comment]
The API has shipped already in webkit, right?

@sefeng211

**Comment by mfreed7** [comment]
I think that's a prototype implementation, though, right? The spec hasn't been reviewed by another implementer that I know of. Or perhaps Mozilla did?

Anyway, this seems reasonable. We will now have this pattern three places, `getHTML()`, `caretPositionFromPoint()`, and here with `getComposedRanges()` - it would be good if they all followed the same pattern.

**Comment by sefeng211** [comment]
Yeah it's shipped in Webkit. cc @rniwa

**Comment by dizhang168** [comment]
Even though Webkit has shipped getComposedRanges, this question is still unanswered.
@rniwa @sefeng211 What do you think of this proposal?

**Comment by sefeng211** [comment]
Looks reasonable to me

**Comment by sanketj** [comment]
@johanneswilm Can we add this to the agenda for the next Editing WG meeting? I don't have permissions to add the "Agenda+" label.

**Comment by whsieh** [comment]
This seems like a reasonable approach (it's similar to how `focus()` takes a parameter dictionary, as well as other APIs). Tagging a few more folks from Apple:

@rniwa @megangardner @annevk @marcoscaceres, any thoughts?

**Comment by rniwa** [comment]
That seems reasonable although it's possible we'd hit some web compatibility issues given we've already shipped this API.
