### ISSUE TITLE
Add a "Selection interface" section

### ISSUE THREAD

**Issue by foolip** [w3c/selection-api#29]
Most specs have a dedicated section, for important interfaces, so that they can be linked easily:
https://dom.spec.whatwg.org/#interface-document
http://dev.w3.org/csswg/cssom/#the-stylesheet-interface

This would be nice for the Selection API spec as well, at first glance I thought the Selection interface wasn't actually in the spec. Maybe just rename "Definition" to "The Selection Interface" or something.

**Comment by foolip** [comment]
Ping @rniwa. This would be good in order to link directly to right place from HTML. Currently there is no good section, so I'll have to link to the document as a whole.

**Comment by rniwa** [comment]
Should be fixed in https://github.com/w3c/selection-api/commit/76d7a44c4855badc22ce1b8be394c5669abfa1aa.  Let me know if you needed a further change.

**Comment by foolip** [comment]
Looks good, thanks!
