### ISSUE TITLE
Make some arguments optional

### ISSUE THREAD

**Issue by foolip** [w3c/selection-api#30]
In both WebKit and Blink, the arguments of some functions are optional. That includes some nonsensical cases like "void addRange([Default=Undefined] optional Range range);" but also some arguments that have sensible defaults:
collapse's offset argument (0)
extend's offset argument (0)
containsNode's allowPartialContainment argument (false)

setBaseAndExtent also has all optional arguments, but that makes less sense.

Consider making at least the first three cases optional, as it does not seem worthwhile investigating the Web compat impact of making them non-optional.

**Comment by foolip** [comment]
Friendly ping. There's a CL for Blink to make the allowPartialContainment argument non-optional, but it makes more sense to keep it optional IMHO. https://codereview.chromium.org/1308663003/

**Comment by foolip** [comment]
We're keeping the allowPartialContainment optional in Blink for now.

**Comment by foolip** [comment]
Ping @rniwa

**Comment by rniwa** [comment]
Which arguments are you suggesting to make optional?

**Comment by foolip** [comment]
To begin with, those mentioned in the initial comment:

> collapse's offset argument (0)
> extend's offset argument (0)
> containsNode's allowPartialContainment argument (false)

I'm not sure what to do with setBaseAndExtent.

**Comment by rniwa** [comment]
Are they required for Web compatibility?  Or are you suggesting it as a developer ergonomics improvement?

**Comment by foolip** [comment]
I'm suggesting the change as the shortest path to interoperability, given that these arguments are already optional in WebKit and Blink, and making something optional (for Edge and Gecko) is lower risk than the other way around. Whether or not it's required for web compatibility I don't know.

Of course, if they are made non-optional in WebKit and that is successfully shipped, then I'd be happy to do the same in Blink, as that would then be the shortest path to interop.

**Comment by foolip** [comment]
Ping @rniwa

**Comment by rniwa** [comment]
I would need a comprehensive list of arguments to be made optional.  I can do the research on my own but that would need more time since I'm focusing on web components work at the moment.

**Comment by foolip** [comment]
I've submitted a pull request to make it unambiguous, PTAL.

The fate of `setBaseAndExtent` will be determined by this use counter which has not yet reached the stable channel: https://www.chromestatus.com/metrics/feature/timeline/popularity/1084

And then there's also the `modify` method that is the topic of #37

I think it's fine to close this issue with the current PR merged though, I'll open a new issue if anything else needs to be optional later.

**Comment by rniwa** [comment]
Thanks! merged.
