### ISSUE TITLE
unsigned long is never negative

### ISSUE THREAD

**Issue by foolip** [w3c/selection-api#33]
The steps for collapse() and setBaseAndExtent include checks for negative numbers, which cannot be true. (These are signed in WebKit/Blink, I guess the steps were just copied.)

**Comment by rniwa** [comment]
So major browsers behave differently according to http://jsfiddle.net/bwLsspuk/

Both WebKit and Blink doesn't do anything (since their IDL says offset is signed long).  Firefox throws an exception.  Does WebIDL automatically throws IndexSizeError when we try to coerce a negative number to an unsigned long type?

**Comment by rniwa** [comment]
@annevk?

**Comment by annevk** [comment]
Per https://heycam.github.io/webidl/#es-unsigned-long I don't think so, unless I'm missing something, but if Firefox throws it seems likely that is due to IDL which only has "unsigned long" and no attributes...

http://mxr.mozilla.org/mozilla-central/source/dom/webidl/Selection.webidl

**Comment by foolip** [comment]
At least in Blink, it looks like passing -1 as an unsigned long argument will get converted to 2^32-1, it's only if [`[EnforceRange]`](https://heycam.github.io/webidl/#EnforceRange) is used that the bindings layer would throw an exception.

**Comment by foolip** [comment]
To be clear, Blink would still throw an exception, but because the offset is too large in the C++, not because it's negative in Bindings.

Tested with another method which actually has an unsigned long argument in Blink: http://jsconsole.com/?new%20Text().insertData(-1%2C"")

**Comment by foolip** [comment]
Also relevant is that we're not really sure how to change the arguments to unsigned in Blink:
https://codereview.chromium.org/1195833002/

@rniwa, are you going to make this change in WebKit, and how would you deal with the range between 2^31 and 2^32-1 if the internal offsets are all still int?

**Comment by rniwa** [comment]
I don't think it's impossible to fix this in WebKit.  However, can you create a TextNode of a length greater than 2^31-1 or a ParentNode with more than 2^31-1 children?  If not, then this would be a moot point.

**Comment by foolip** [comment]
I don't think that would be disallowed by any spec, but I see that V8 has a limit on string lengths, `static const int kMaxLength = (1 << 28) - 16`.

You can get a Text node with a greater length with that:
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3594

However, I can't get a Text node with length 2^31 by increasing the number of copies before normalize, it crashes.

As for child nodes, testing that would take way too much memory.

I guess it's reasonable for the specs to pretend that 2^32 is the limit, and there can be lower limits that we call "platform limitations".

**Comment by rniwa** [comment]
It appears to me that implicitly coercing -1 to 2^32 is worse than throwing an exception or ceiling to 0 by accepting signed long instead.

**Comment by foolip** [comment]
It would still throw an exception, just not for the same reason. But I'd be quite happy to see all the offsets changed to long instead, since that's what Blink already has in its IDL. However, then Gecko would have to change instead.

**Comment by rniwa** [comment]
Alright, that seems fine then.  I removed the mentioning of negative values from the spec in the above commit.  Please reopen the issue if the above change is not sufficient.

**Comment by Tanayc** [comment]
Trying a similar change in https://codereview.chromium.org/1269263003/
This becomes very messy in Blink. 

@rniwa  Are you making this change in Webkit or should the spec be changed instead?
