### ISSUE TITLE
Expand selectstart to cover use cases for contenteditable=typing

### ISSUE THREAD

**Issue by rniwa** [w3c/selection-api#45]
See use cases listed at https://github.com/w3c/editing/issues/58#issuecomment-108860806

**Comment by rniwa** [comment]
Please don't close issues without stating why.

**Comment by johanneswilm** [comment]
Closed because cE=events has no default caret movement. Therefore the use cases no longer apply.

**Comment by rniwa** [comment]
Okay, so we don't need any extensions to this event.
