### ISSUE TITLE
Is Selection.removeAllRanges() and Selection.removeRange(range) doing the same thing?

### ISSUE THREAD

**Issue by paritosh-in** [w3c/selection-api#48]
- **As Selection.removeAllRanges() and Selection.removeRange(range) uses the same statement**  
    `The method must make the context object empty by disassociating its range if the context object's range is` _range_.`Otherwise, it must do nothing.`

One more point, what is _range_, in Selection.removeAllRanges() when we are saying `if the context object's range is` _range_`.

**Comment by rniwa** [comment]
Thanks! Fixed it in the commit above.
