### ISSUE TITLE
Should selectionchange be fired when the Range object is directly mutated

### ISSUE THREAD

**Issue by mystor** [w3c/selection-api#52]
If the range object is directly mutated by the user script, should the selectionchange event be fired? This isn't clear in the documentation.

``` javascript
var s = document.getSelection();
var r = document.createRange();
r.selectNode(node1);
s.addRange(r); // selectionchange event should be queued
// -- some time passes --
r.selectNode(node2); // Should another selectionchange event be queued?
```

**Comment by timdown** [comment]
Surely yes, iff mutating the range changes the selection.

**Comment by rniwa** [comment]
Most certainly. I tried to clarify that in the commit above.  Please reopen the issue if the change is not sufficient to address your concern.
