### ISSUE TITLE
The node argument of collapse and setPosition should be nullable

### ISSUE THREAD

**Issue by foolip** [w3c/selection-api#64]
Passing null should cause it to behave like `removeAllRanges`. This is the behavior of WebKit and Blink, and an attempt to align with the spec in Blink failed with many reports of breakage:
https://code.google.com/p/chromium/issues/detail?id=395318

**Comment by rniwa** [comment]
Please re-open the issue if the above commit doesn't adequately address the issue.

**Comment by foolip** [comment]
Thanks!
