### ISSUE TITLE
setBaseAndExtent() and setPositon() should be marked as "deprecated"

### ISSUE THREAD

**Issue by yosinch** [w3c/selection-api#67]
setBaseAndExtent() and setPositon() are introduced by Blink/WebKit. setBaseAndExtent() doesn't match in current term "anchor" and "focus". setPosition() is a just alias of collapse().

**Comment by rniwa** [comment]
What's the point of marking them as deprecated?  I don't think there is anything wrong with these methods.  Also, Blink/WebKit should eventually match the spec or the spec should change to match the current WebKit/Blink behavior over time.  The fact existing implementations don't match the current specification is no way to justify deprecation of an API.

**Comment by gked** [comment]
+1 on rniwa's argument. I think, now all browsers(well, I am not sure about FF but Blink/WebKit/Edge) support both conventions through aliasing. Should spec perhaps match this?

**Comment by rniwa** [comment]
The spec already has both of these methods.

**Comment by gked** [comment]
@yosinch: are you satisfied with our reasoning? can we close the issue?
