### ISSUE TITLE
Bahavior without browsing context

### ISSUE THREAD

**Issue by tkent-google** [w3c/selection-api#82]
The specification doesn't define ```Selection``` interface behavior in a case where browsing context was lost.

```
<!DOCTYPE html>
<iframe src="about:blank"></iframe>
<p>abc</p>
<script>
window.onload = function() {
    var iframe = document.querySelector('iframe');
    var selection = iframe.contentWindow.getSelection();
    iframe.remove();
    selection.removeAllRanges();
    var range = document.createRange();
    range.setStart(document, 0);
    selection.addRange(range);
    selection.extend(document, 1);
    alert('rangeCount=' + selection.rangeCount);
};
</script>
```

With this code,
Safari, Edge, and Chrome: ```selection``` functions look to do nothing.  ```alert()``` shows "rangeCount=0"
Firefox: ```addRange()``` succeeds, but ```extend()``` results in ```NS_ERROR_FAILURE```

**Comment by rniwa** [comment]
Okay, it looks like we can just spec Safari/Edge/Chrome behavior here unless Firefox encounters a compatibility problem to change their behavior.

**Comment by annevk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1612792 tracks this for Firefox (no progress yet).

**Comment by rniwa** [comment]
@annevk : Any opinion / objection to matching the existing behavior of Safari/Edge/Chrome?

**Comment by annevk** [comment]
That seems like the way to go to me.

**Comment by rniwa** [comment]
Firefox has since changed its behavior to match Blink/WebKit, and the spec already specifies this behavior: https://www.w3.org/TR/selection-api/#extensions-to-document-interface
