### ISSUE TITLE
edge 中selection.focusOffset计算错误

### ISSUE THREAD

**Issue by zhangyonglan** [w3c/selection-api#97]
在Edge中，选中文本的最后一个词语，Selection.focusOffset计算错误。

**Comment by rniwa** [comment]
Translation by my colleague:
> The calculation of selection.focusOffset in edge is wrong.
>
> In Edge, select the last word in the text, Selection.focusOffset is wrong.

**Comment by rniwa** [comment]
Looks like this is an issue with Microsoft Edge, and not so much with the spec. Closing for now.
