### ISSUE TITLE
Add getComposedRange to Selection

### ISSUE THREAD

**Issue by rniwa** [w3c/selection-api#98]
Per https://github.com/w3c/webcomponents/issues/79, we should add `getComposedRange` which takes a sequence of `ShadowRoot` to `Selection` and return a `StaticRange`.

**Comment by rniwa** [comment]
I think probably prioritize this over other issues since not being able to use selection is a major roadblock for shadow DOM users as far as I know.

**Comment by rniwa** [comment]
@smaug---- @annevk could you take a look at https://w3c.github.io/selection-api/#dom-selection-getcomposedrange and see if it makes sense?

**Comment by annevk** [comment]
Filed https://github.com/w3c/selection-api/issues/161.
